export const IPC_CHANNELS = {
  appVersion: "app:version",
  securityState: "app:security-state",
  workspaceOpen: "workspace:open",
  workspaceList: "workspace:list",
  agentCreate: "agent:create",
  agentList: "agent:list",
  agentListEvents: "agent:list-events",
  agentListRuns: "agent:list-runs",
  agentEnsure: "agent:ensure",
  agentPrompt: "agent:prompt",
  agentAbort: "agent:abort",
  agentSetModel: "agent:set-model",
  agentCycleModel: "agent:cycle-model",
  agentEvent: "agent:event",
  terminalCreate: "terminal:create",
  terminalWrite: "terminal:write",
  terminalResize: "terminal:resize",
  terminalKill: "terminal:kill",
  terminalList: "terminal:list",
  terminalEvent: "terminal:event",
  diffList: "diff:list",
  diffRead: "diff:read",
  diffRevert: "diff:revert",
  diffStage: "diff:stage",
  diffUnstage: "diff:unstage",
  diffDiscard: "diff:discard",
  diffCommit: "diff:commit",
  reviewStart: "review:start",
  reviewList: "review:list",
  worktreeList: "worktree:list",
  worktreeCreate: "worktree:create",
  worktreeDelete: "worktree:delete",
  permissionDecide: "permission:decide",
  permissionList: "permission:list",
  contextSearch: "context:search",
  contextResolve: "context:resolve",
  docsList: "docs:list",
  docsAdd: "docs:add",
  docsSearch: "docs:search",
  modelList: "model:list",
  modelSetDefault: "model:set-default",
  modelSettings: "model:settings",
  modelProviderDetail: "model:provider-detail",
  modelConfigureProvider: "model:configure-provider",
  modelUpsertCustomProvider: "model:upsert-custom-provider",
  modelUpdateConfig: "model:update-config",
  // 自绘 titlebar：renderer 调 IPC 触发 window 操作，main 反推 maximize 状态以同步图标
  windowMinimize: "window:minimize",
  windowToggleMaximize: "window:toggle-maximize",
  windowClose: "window:close",
  windowState: "window:state",
  windowStateEvent: "window:state-event",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
