export const IPC_CHANNELS = {
  appVersion: "app:version",
  securityState: "app:security-state",
  workspaceOpen: "workspace:open",
  workspaceList: "workspace:list",
  agentCreate: "agent:create",
  agentPrompt: "agent:prompt",
  agentAbort: "agent:abort",
  agentEvent: "agent:event",
  terminalCreate: "terminal:create",
  terminalWrite: "terminal:write",
  terminalResize: "terminal:resize",
  terminalKill: "terminal:kill",
  terminalEvent: "terminal:event",
  diffList: "diff:list",
  diffRead: "diff:read",
  diffRevert: "diff:revert",
  worktreeList: "worktree:list",
  worktreeCreate: "worktree:create",
  worktreeDelete: "worktree:delete",
  permissionDecide: "permission:decide",
  permissionList: "permission:list",
  // 自绘 titlebar：renderer 调 IPC 触发 window 操作，main 反推 maximize 状态以同步图标
  windowMinimize: "window:minimize",
  windowToggleMaximize: "window:toggle-maximize",
  windowClose: "window:close",
  windowState: "window:state",
  windowStateEvent: "window:state-event",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
